/**
 * Drizzle schema for SERVIO Kargo (PostgreSQL).
 *
 * Core tables from CLAUDE.md "Data Model" plus the SPEC.md 7.8 `deleted_at`
 * soft-delete extension on `tracks`.
 *
 * Conventions:
 * - Primary keys: uuid (gen_random_uuid, built into Postgres).
 * - Money: bigint tiyin (integer minor unit, never floats) — CLAUDE.md rule 6.
 * - Telegram user ids: bigint (they exceed int4).
 * - Timestamps: timestamptz stored in UTC — SPEC 7.9.
 * - Every domain table carries tenant_id — CLAUDE.md rule 1.
 */

import { relations, sql } from 'drizzle-orm';
import {
  type AnyPgColumn,
  bigint,
  boolean,
  date,
  index,
  integer,
  jsonb,
  pgEnum,
  pgTable,
  primaryKey,
  text,
  timestamp,
  uniqueIndex,
  uuid,
} from 'drizzle-orm/pg-core';

// --- Enums -----------------------------------------------------------------

/** Fixed status pipeline (CLAUDE.md rule 7) in canonical order + side-states. */
export const trackStatus = pgEnum('track_status', [
  'CREATED',
  'CHINA_WAREHOUSE',
  'IN_TRANSIT',
  'TASHKENT_WAREHOUSE',
  'READY_FOR_PICKUP',
  'DELIVERED',
  'LOST',
  'RETURNED',
]);

/**
 * Panel + bot roles, in descending authority (SPEC §1). They name a JOB, not a
 * power level: a Tashkent cargo runs an owner, office managers and warehouse
 * hands, and each needs a different screen — see `ROLE_CAPABILITIES` in
 * `@kargotrack/shared`, which is the single source of truth for who may do what.
 *
 * `staff` is the legacy value kept so pre-existing rows stay readable; the
 * migration rewrites every one of them to `manager` and nothing issues it again.
 */
export const adminRole = pgEnum('admin_role', [
  'owner',
  'manager',
  'warehouse',
  'staff',
]);

export const paymentMethod = pgEnum('payment_method', [
  'cash',
  'click',
  'payme',
  'other',
]);

export const lang = pgEnum('lang', ['uz', 'ru']);

/** What kind of outbound bot message a `message_log` row records. */
export const messageKind = pgEnum('message_kind', [
  'notify',
  'reminder',
  'broadcast',
  // Staff ticket reply / closure delivery (SPEC §7.15).
  'ticket',
]);

/** Ticket dispute categories — the fixed D-004 five (SPEC §7.15). */
export const ticketCategory = pgEnum('ticket_category', [
  'weight',
  'damage',
  'lost',
  'payment',
  'other',
]);

export const ticketStatus = pgEnum('ticket_status', [
  'open',
  'in_progress',
  'closed',
]);

/** Who wrote a ticket message (SPEC §7.15). */
export const ticketAuthor = pgEnum('ticket_author', ['customer', 'staff']);

/**
 * Delivery outcome. `sent` = Telegram accepted it; `dropped` = permanently
 * unreachable (blocked the bot, deleted the chat); `failed` = gave up after
 * every retry on a transient error.
 */
export const messageDeliveryStatus = pgEnum('message_delivery_status', [
  'sent',
  'dropped',
  'failed',
]);

/** Tenant billing currency (SPEC §5.9 / §7.4). */
export const currency = pgEnum('currency', ['UZS', 'USD']);

/** Batch transport mode (SPEC §5.7). */
export const transport = pgEnum('transport', ['avia', 'avto', 'train']);

/**
 * Subscription tier. Which features each tier unlocks is answered ONLY by
 * `planIncludes` in `@kargotrack/shared` (services/plans.ts) — the same
 * single-source rule the permission matrix follows.
 */
export const tenantPlan = pgEnum('tenant_plan', ['basic', 'premium']);

// --- Shared shapes ---------------------------------------------------------

/** Tenant-level configuration stored in `tenants.settings`. */
export type TenantSettings = {
  /**
   * @deprecated Superseded by `admin_users.tg_user_id` (AUDIT.md T8). Staff mode
   * now resolves a real employee row — with a role — instead of a bare id, so
   * the bot can tell a warehouse hand from an owner and the audit trail can name
   * them. Migration 0009 copied every id here into `admin_users`; the field is
   * retained only so a rollback can still read old rows, and nothing writes it.
   */
  staff_tg_ids?: number[];
  /** Weekly auto-reminder config (SPEC 5.7 / 7.7). */
  reminders: {
    weekly_enabled: boolean;
    /** 1 = Monday … 7 = Sunday (ISO). */
    weekday: number;
    /** Hour of day in Asia/Tashkent, 0–23. */
    hour: number;
  };
  /**
   * China-warehouse address template rendered in the bot (SPEC 3.10 / 5.9).
   * `{client_code}` is substituted with the customer's code. Optional — older
   * rows and freshly onboarded tenants may not have it set yet.
   */
  china_address_template?: string;
  /** Free-text info block shown in the bot Info card (SPEC 3.5 / 5.9). */
  info_text?: string;
  /**
   * Marks a throwaway tenant generated by the demo importer
   * (packages/db/scripts/demo-import.ts) from a prospect's Telegram channel
   * history. Real onboarded tenants never set this. jsonb, so no migration.
   */
  demo?: boolean;
};

// --- Tables ----------------------------------------------------------------

export const tenants = pgTable('tenants', {
  id: uuid('id').primaryKey().defaultRandom(),
  name: text('name').notNull(),
  // Client-code prefix (2–4 latin letters, e.g. "DK"). client_code =
  // code_prefix + '-' + per-tenant sequence (SPEC 6, customers.client_code).
  codePrefix: text('code_prefix').notNull(),
  botToken: text('bot_token').notNull().unique(),
  botUsername: text('bot_username'),
  // Billing currency + USD rate (SPEC §5.9 / §7.4). Per-kg prices live on
  // `tariffs`, not here. `usd_rate_tiyin` = som per 1 USD, in tiyin; used only
  // when currency = 'USD'.
  currency: currency('currency').notNull().default('UZS'),
  usdRateTiyin: bigint('usd_rate_tiyin', { mode: 'number' }),
  plan: tenantPlan('plan').notNull().default('basic'),
  pickupAddress: text('pickup_address'),
  workingHours: text('working_hours'),
  contactPhone: text('contact_phone'),
  settings: jsonb('settings').$type<TenantSettings>().notNull(),
  createdAt: timestamp('created_at', { withTimezone: true })
    .notNull()
    .defaultNow(),
});

/**
 * Per-tenant pricing tariffs (SPEC §5.9, §7.4). A tenant always has exactly one
 * active default tariff (enforced in the service layer, not the DB).
 * `price_per_kg_minor` is tiyin when the tenant is UZS, cents when USD.
 */
export const tariffs = pgTable('tariffs', {
  id: uuid('id').primaryKey().defaultRandom(),
  tenantId: uuid('tenant_id')
    .notNull()
    .references(() => tenants.id, { onDelete: 'cascade' }),
  name: text('name').notNull(),
  pricePerKgMinor: bigint('price_per_kg_minor', { mode: 'number' }).notNull(),
  // Volumetric coefficient in kg per m³ (SPEC §7.16, D-007). 167 is the
  // 1:6000 air-freight standard; a road tariff usually wants 200–333. It only
  // ever matters for a parcel whose dimensions were entered.
  volumetricCoef: integer('volumetric_coef').notNull().default(167),
  isDefault: boolean('is_default').notNull().default(false),
  active: boolean('active').notNull().default(true),
  sort: integer('sort').notNull().default(0),
  createdAt: timestamp('created_at', { withTimezone: true })
    .notNull()
    .defaultNow(),
});

/**
 * Shipment batches ("Reyslar", SPEC §5.7, §7.10). Tracks optionally reference a
 * batch; a batch status change propagates to its non-terminal member tracks. A
 * batch's own status is limited to CHINA_WAREHOUSE | IN_TRANSIT |
 * TASHKENT_WAREHOUSE (enforced in the service layer).
 */
export const batches = pgTable('batches', {
  id: uuid('id').primaryKey().defaultRandom(),
  tenantId: uuid('tenant_id')
    .notNull()
    .references(() => tenants.id, { onDelete: 'cascade' }),
  name: text('name').notNull(),
  transport: transport('transport').notNull(),
  // Estimated arrival (date only). Shown in bot cards + IN_TRANSIT notifications.
  etaDate: date('eta_date'),
  status: trackStatus('status').notNull().default('CHINA_WAREHOUSE'),
  createdAt: timestamp('created_at', { withTimezone: true })
    .notNull()
    .defaultNow(),
});

/**
 * One row per employee of a cargo company — the SAME row on both surfaces.
 *
 * It used to be two disconnected identities: this table for the panel and
 * `tenants.settings.staff_tg_ids` for the bot's weighing mode. A warehouse hand
 * therefore existed twice under two different keys, and the audit log could only
 * say `staff:123456789` or a bare uuid. `tg_user_id` collapses them, so
 * "who weighed this" and "who logged in" name one person (AUDIT.md T8).
 *
 * `phone` and `password_hash` are nullable because bot-only staff are real:
 * every id migrated out of `staff_tg_ids` became a row here with neither, and an
 * owner can invite them to the panel later (see `adminInvites`).
 */
export const adminUsers = pgTable(
  'admin_users',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    tenantId: uuid('tenant_id')
      .notNull()
      .references(() => tenants.id, { onDelete: 'cascade' }),
    // Null until the person is given panel access. Both of these are null
    // together — `canSignIn` in @kargotrack/shared is the one place that decides.
    phone: text('phone'),
    passwordHash: text('password_hash'),
    /** Telegram id, for bot staff mode (SPEC §3.8). Null until they link it. */
    tgUserId: bigint('tg_user_id', { mode: 'number' }),
    /** Display name for the audit trail — a uuid tells nobody anything. */
    fullName: text('full_name'),
    role: adminRole('role').notNull().default('manager'),
    // Admin panel UI language (next-intl locale). Independent of `customers.lang`:
    // Tashkent office staff often work in Russian while their customers read
    // Uzbek. Defaults to 'uz' — the panel's default locale.
    lang: lang('lang').notNull().default('uz'),
    /**
     * Soft off-switch. Employees leave; their rows must stay so the tracks and
     * payments they touched keep naming them, so departure flips this instead of
     * deleting. Sign-in and bot staff mode both require it.
     */
    active: boolean('active').notNull().default(true),
    /**
     * Bumped to revoke every issued session token for this admin (password
     * change, "sign out everywhere", deactivation). Sessions are stateless
     * signed cookies valid for 30 days, so without this a departing employee's
     * phone kept working for a month and there was no way to stop it.
     */
    sessionEpoch: integer('session_epoch').notNull().default(0),
    lastLoginAt: timestamp('last_login_at', { withTimezone: true }),
    createdAt: timestamp('created_at', { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => ({
    // Login looks admins up by phone alone (phone is NOT unique across tenants,
    // so every match is argon2-verified) — without this the login path seq-scans.
    phoneIdx: index('admin_users_phone_idx').on(t.phone),
    // Two employees of ONE cargo cannot share a number — that would make the
    // audit trail ambiguous and the invite flow pick a row at random. Across
    // tenants it stays legal: one person may work for two companies.
    tenantPhoneUq: uniqueIndex('admin_users_tenant_phone_uq')
      .on(t.tenantId, t.phone)
      .where(sql`${t.phone} IS NOT NULL`),
    // The bot resolves staff by (tenant, telegram id) on every update.
    tenantTgUserUq: uniqueIndex('admin_users_tenant_tg_user_uq')
      .on(t.tenantId, t.tgUserId)
      .where(sql`${t.tgUserId} IS NOT NULL`),
    // The team screen lists a tenant's employees.
    tenantIdx: index('admin_users_tenant_idx').on(t.tenantId),
  }),
);

/**
 * Pending panel invitations (SPEC §5.12).
 *
 * An owner never types a colleague's password: knowing it would let them act as
 * that person, which is exactly what `track_events.created_by` and
 * `payments.created_by` are supposed to rule out. So the owner creates an invite
 * and the invitee sets their own password with the code.
 *
 * The code is stored in the clear on purpose — an owner has to be able to
 * re-read it an hour later when the new hire finally answers the phone. It is
 * safe to: it is six characters from a 32-symbol alphabet (~10^9), scoped to one
 * phone in one tenant, expires in 24 hours, and dies on first use.
 */
export const adminInvites = pgTable(
  'admin_invites',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    tenantId: uuid('tenant_id')
      .notNull()
      .references(() => tenants.id, { onDelete: 'cascade' }),
    /**
     * The admin row this invite belongs to. Created up front so the person shows
     * up on the team screen as "pending" and can be given a role and a Telegram
     * link before they ever open the panel.
     */
    adminUserId: uuid('admin_user_id')
      .notNull()
      .references(() => adminUsers.id, { onDelete: 'cascade' }),
    code: text('code').notNull(),
    expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
    acceptedAt: timestamp('accepted_at', { withTimezone: true }),
    createdBy: uuid('created_by').references(() => adminUsers.id, {
      onDelete: 'set null',
    }),
    createdAt: timestamp('created_at', { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => ({
    // Indexed on the code ALONE, deliberately: redemption happens on /login,
    // which has no tenant yet — the person types a phone and a code, and the
    // tenant is whatever the matching row turns out to belong to. The bot's
    // Telegram-linking flow does know its tenant and filters after the lookup.
    codeIdx: index('admin_invites_code_idx').on(t.code),
    // At most one live invite per employee — a second `Invite` replaces it.
    adminUq: uniqueIndex('admin_invites_admin_uq')
      .on(t.adminUserId)
      .where(sql`${t.acceptedAt} IS NULL`),
  }),
);

export const customers = pgTable(
  'customers',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    tenantId: uuid('tenant_id')
      .notNull()
      .references(() => tenants.id, { onDelete: 'cascade' }),
    tgUserId: bigint('tg_user_id', { mode: 'number' }),
    phone: text('phone'),
    // Comparison key for `phone` — last 9 digits (SPEC §7.12,
    // `normalizePhone`). Always written together with `phone`; it is what the
    // panel's duplicate check and the bot's "link my hand-entered record"
    // lookup match on, because the same number arrives spelled three ways.
    phoneNormalized: text('phone_normalized'),
    fullName: text('full_name'),
    clientCode: text('client_code').notNull(),
    lang: lang('lang').notNull().default('uz'),
    /** Employee who hand-entered this customer; null when the bot registered them. */
    createdBy: uuid('created_by').references(() => adminUsers.id, {
      onDelete: 'set null',
    }),
    createdAt: timestamp('created_at', { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => ({
    // client_code is unique within a tenant.
    clientCodeUq: uniqueIndex('customers_tenant_client_code_uq').on(
      t.tenantId,
      t.clientCode,
    ),
    // A Telegram user maps to at most one customer per tenant.
    tgUserUq: uniqueIndex('customers_tenant_tg_user_uq').on(
      t.tenantId,
      t.tgUserId,
    ),
    // Deliberately NOT unique: production data predates the column and a
    // company may legitimately hold two records for one number until an admin
    // merges them. Duplicates are refused in the app (createCustomer), where a
    // clash can be reported instead of aborting a bot registration mid-flow.
    phoneIdx: index('customers_tenant_phone_idx').on(
      t.tenantId,
      t.phoneNormalized,
    ),
  }),
);

export const tracks = pgTable(
  'tracks',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    tenantId: uuid('tenant_id')
      .notNull()
      .references(() => tenants.id, { onDelete: 'cascade' }),
    // Nullable: codes can arrive before a customer claims them (CLAUDE.md).
    customerId: uuid('customer_id').references(() => customers.id, {
      onDelete: 'set null',
    }),
    // Pricing tariff (SPEC §7.4); set to the tenant's default when first weighed.
    tariffId: uuid('tariff_id').references(() => tariffs.id, {
      onDelete: 'set null',
    }),
    // Shipment batch (SPEC §7.10), optional.
    batchId: uuid('batch_id').references(() => batches.id, {
      onDelete: 'set null',
    }),
    codeNormalized: text('code_normalized').notNull(),
    codeOriginal: text('code_original').notNull(),
    currentStatus: trackStatus('current_status').notNull().default('CREATED'),
    weightGrams: integer('weight_grams'),
    // Som price, always populated once weighed (frozen for USD tenants, §7.4).
    priceTiyin: bigint('price_tiyin', { mode: 'number' }),
    // USD-mode extras: price in cents + the som-per-USD rate used at weighing.
    priceUsdCents: bigint('price_usd_cents', { mode: 'number' }),
    usdRateUsed: bigint('usd_rate_used', { mode: 'number' }),
    // Manual override (§7.4): admin typed a som price; suspends auto-recompute.
    priceManual: boolean('price_manual').notNull().default(false),
    // SPEC 7.13 metadata. `marka` is what the box SAYS (evidence), never who
    // owns the parcel; `note` is panel-only and must not reach the customer.
    marka: text('marka'),
    description: text('description'),
    note: text('note'),
    // SPEC 7.16 volumetric pricing. Dimensions in whole centimetres, only
    // meaningful all three together. `volumetric_grams` is the weight those
    // dimensions bought at the tariff's coefficient, FROZEN when the price was
    // written — the same stance as `usd_rate_used`, so editing a coefficient
    // later never makes an old track's displayed weight contradict its price.
    lengthCm: integer('length_cm'),
    widthCm: integer('width_cm'),
    heightCm: integer('height_cm'),
    volumetricGrams: integer('volumetric_grams'),
    // SPEC 7.8 soft delete.
    deletedAt: timestamp('deleted_at', { withTimezone: true }),
    createdAt: timestamp('created_at', { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => ({
    // CLAUDE.md: codes unique per tenant; collisions across tenants are fine.
    codeUq: uniqueIndex('tracks_tenant_code_uq').on(
      t.tenantId,
      t.codeNormalized,
    ),
    customerIdx: index('tracks_customer_idx').on(t.customerId),
    batchIdx: index('tracks_batch_idx').on(t.batchId),
    // The tracks list (SPEC §5.2) is always
    //   tenant_id = ? AND deleted_at IS NULL ORDER BY created_at DESC LIMIT 20
    // These two are PARTIAL on `deleted_at IS NULL` on purpose. It is not about
    // index size (few rows are soft-deleted) — it is that a partial index whose
    // predicate matches the query lets the planner walk the index in order and
    // stop at the LIMIT. With a plain index the planner instead bitmap-scans
    // every row of the tenant and top-N sorts: measured 56 ms vs 0.75 ms on
    // 40 000 tracks. Every list/filter/detail read filters soft-deletes (§7.8),
    // so the predicate is always present. The import path deliberately *includes*
    // soft-deleted rows, but it matches on `tracks_tenant_code_uq` instead.
    //
    // `.nullsFirst()` is REQUIRED, not cosmetic: SQL `ORDER BY x DESC` means
    // DESC NULLS FIRST, while Drizzle's bare `.desc()` emits DESC NULLS *LAST*.
    // The two don't match, so the planner silently falls back to a full sort —
    // measured 47.9 ms (NULLS LAST) vs 0.60 ms (NULLS FIRST) for the same index.
    tenantCreatedIdx: index('tracks_tenant_created_idx')
      .on(t.tenantId, t.createdAt.desc().nullsFirst())
      .where(sql`${t.deletedAt} IS NULL`),
    // Status filter chips + every "count by status" read.
    tenantStatusIdx: index('tracks_tenant_status_idx')
      .on(t.tenantId, t.currentStatus)
      .where(sql`${t.deletedAt} IS NULL`),
  }),
);

/** Why a photo was taken (SPEC 7.14). */
export const photoKind = pgEnum('photo_kind', [
  'intake',
  'damage',
  'handover',
]);

/**
 * A parcel's photos (SPEC 7.14, tasks.md H2) — many per track, never
 * overwritten. `path` is the file's actual relative path under the uploads
 * root: new shots go to `{tenantId}/{trackId}/{photoId}.jpg`, rows migrated
 * from the single-photo era still point at `{tenantId}/{trackId}.jpg`.
 */
export const trackPhotos = pgTable(
  'track_photos',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    tenantId: uuid('tenant_id')
      .notNull()
      .references(() => tenants.id, { onDelete: 'cascade' }),
    trackId: uuid('track_id')
      .notNull()
      .references(() => tracks.id, { onDelete: 'cascade' }),
    kind: photoKind('kind').notNull().default('intake'),
    path: text('path').notNull(),
    // Free-form actor, same convention as track_events.created_by.
    createdBy: text('created_by'),
    createdAt: timestamp('created_at', { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => ({
    // The gallery, the notification attach and every hasPhoto EXISTS all ask
    // "photos of THIS track, newest first".
    trackIdx: index('track_photos_track_idx').on(
      t.trackId,
      t.createdAt.desc().nullsFirst(),
    ),
  }),
);

export type TrackPhoto = typeof trackPhotos.$inferSelect;

/**
 * A customer's dispute (SPEC §7.15, tasks.md H3 — D-004/D-006): one problem,
 * one thread. The customer writes from the bot; staff reply from the panel.
 */
export const tickets = pgTable(
  'tickets',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    tenantId: uuid('tenant_id')
      .notNull()
      .references(() => tenants.id, { onDelete: 'cascade' }),
    customerId: uuid('customer_id')
      .notNull()
      .references(() => customers.id, { onDelete: 'cascade' }),
    // Optional bound parcel; the dispute outlives a deleted track row.
    trackId: uuid('track_id').references(() => tracks.id, {
      onDelete: 'set null',
    }),
    category: ticketCategory('category').notNull(),
    status: ticketStatus('status').notNull().default('open'),
    // Workflow aid, not a permission (SPEC §5.16).
    assignedTo: uuid('assigned_to').references(() => adminUsers.id, {
      onDelete: 'set null',
    }),
    // Orders every list; bumped on each message (§7.15).
    lastMessageAt: timestamp('last_message_at', { withTimezone: true })
      .notNull()
      .defaultNow(),
    createdAt: timestamp('created_at', { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => ({
    // The §5.16 list: tenant + status chips, newest activity first.
    tenantStatusIdx: index('tickets_tenant_status_idx').on(
      t.tenantId,
      t.status,
      t.lastMessageAt.desc().nullsFirst(),
    ),
    // The bot's "does this customer have a ticket?" entry question (§3.13).
    tenantCustomerIdx: index('tickets_tenant_customer_idx').on(
      t.tenantId,
      t.customerId,
      t.lastMessageAt.desc().nullsFirst(),
    ),
  }),
);

export type Ticket = typeof tickets.$inferSelect;

/** One message of a ticket's thread — append-only (SPEC §7.15). */
export const ticketMessages = pgTable(
  'ticket_messages',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    tenantId: uuid('tenant_id')
      .notNull()
      .references(() => tenants.id, { onDelete: 'cascade' }),
    ticketId: uuid('ticket_id')
      .notNull()
      .references(() => tickets.id, { onDelete: 'cascade' }),
    author: ticketAuthor('author').notNull(),
    // customers.id or admin_users.id, per `author` — free-form like
    // track_events.created_by, resolved for display at read time.
    authorId: text('author_id'),
    text: text('text').notNull(),
    createdAt: timestamp('created_at', { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => ({
    // The thread read: one ticket's messages in order.
    ticketIdx: index('ticket_messages_ticket_idx').on(
      t.ticketId,
      t.createdAt,
    ),
  }),
);

export type TicketMessage = typeof ticketMessages.$inferSelect;

export const trackEvents = pgTable(
  'track_events',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    trackId: uuid('track_id')
      .notNull()
      .references(() => tracks.id, { onDelete: 'cascade' }),
    status: trackStatus('status').notNull(),
    meta: jsonb('meta'),
    // Free-form actor: 'system', an admin_user id, or a telegram id.
    createdBy: text('created_by'),
    createdAt: timestamp('created_at', { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => ({
    // This is the fastest-growing table (a row per status change) and Postgres
    // does NOT index foreign keys automatically. Without this, the track-detail
    // timeline and the ON DELETE CASCADE both seq-scan the whole log: measured
    // 18.5 ms vs 0.14 ms on 160 000 events. `.nullsFirst()` matches SQL's
    // `ORDER BY created_at DESC` — see the note on tracks_tenant_created_idx.
    trackIdx: index('track_events_track_idx').on(
      t.trackId,
      t.createdAt.desc().nullsFirst(),
    ),
    // Dashboard §5.10 counts events by status inside a period. `track_events`
    // carries no tenant_id, so this index cannot be tenant-scoped — it still
    // turns a full-log scan into a range scan, but the rows of every tenant
    // share it. AUDIT.md T4: if the dashboard is still slow at scale, the fix is
    // to denormalize `tenant_id` onto this table and index (tenant, status, at).
    statusCreatedIdx: index('track_events_status_created_idx').on(
      t.status,
      t.createdAt,
    ),
  }),
);

export const payments = pgTable(
  'payments',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    tenantId: uuid('tenant_id')
      .notNull()
      .references(() => tenants.id, { onDelete: 'cascade' }),
    customerId: uuid('customer_id')
      .notNull()
      .references(() => customers.id, { onDelete: 'cascade' }),
    amountTiyin: bigint('amount_tiyin', { mode: 'number' }).notNull(),
    method: paymentMethod('method').notNull().default('cash'),
    note: text('note'),
    /**
     * Which employee took the money. Cash crosses a counter in this business, so
     * an unattributable payment row is the one gap an owner cannot audit around
     * — this is what makes the owner's "today's cash by employee" read possible
     * (SPEC §5.10). Null only for rows written before the column existed.
     */
    createdBy: uuid('created_by').references(() => adminUsers.id, {
      onDelete: 'set null',
    }),
    /**
     * Storno (tasks.md A7): the payment this row reverses. A cancellation is a
     * NEW row with the negated amount, never an update or delete — the ledger
     * stays append-only and every debt/tushum read nets it out arithmetically.
     * The reason lives in `note`; who cancelled, in `created_by`.
     */
    reversalOf: uuid('reversal_of').references((): AnyPgColumn => payments.id, {
      onDelete: 'restrict',
    }),
    createdAt: timestamp('created_at', { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => ({
    // Debt (§7.5) reads payments per tenant and per customer; the leading
    // tenant_id serves both the tenant-wide sweep and the customer detail.
    tenantCustomerIdx: index('payments_tenant_customer_idx').on(
      t.tenantId,
      t.customerId,
    ),
    // A payment can be reversed at most ONCE — the double-storno guard lives
    // in the database, not just in the app code.
    reversalOfUq: uniqueIndex('payments_reversal_of_uq')
      .on(t.reversalOf)
      .where(sql`${t.reversalOf} IS NOT NULL`),
    // Dashboard tushum card + the 14-day chart: tenant + created_at range.
    tenantCreatedIdx: index('payments_tenant_created_idx').on(
      t.tenantId,
      t.createdAt,
    ),
  }),
);

/**
 * Broadcast history (SPEC §5.8, §7.11). One row per admin broadcast; `sent_count`
 * is bumped by the bot worker as each recipient's message is delivered, so it
 * records the final delivered count.
 */
export const broadcasts = pgTable('broadcasts', {
  id: uuid('id').primaryKey().defaultRandom(),
  tenantId: uuid('tenant_id')
    .notNull()
    .references(() => tenants.id, { onDelete: 'cascade' }),
  text: text('text').notNull(),
  sentCount: integer('sent_count').notNull().default(0),
  /** Employee who pressed send — a broadcast reaches every customer at once. */
  createdBy: uuid('created_by').references(() => adminUsers.id, {
    onDelete: 'set null',
  }),
  createdAt: timestamp('created_at', { withTimezone: true })
    .notNull()
    .defaultNow(),
});

/**
 * Demo requests from the public landing page. Platform-level (a lead is a
 * cargo company that is not a tenant yet), so deliberately no tenant_id.
 */
export const leads = pgTable('leads', {
  id: uuid('id').primaryKey().defaultRandom(),
  name: text('name').notNull(),
  phone: text('phone').notNull(),
  company: text('company'),
  // Which landing locale the form was submitted from (/ = uz, /ru = ru).
  locale: lang('locale').notNull().default('uz'),
  createdAt: timestamp('created_at', { withTimezone: true })
    .notNull()
    .defaultNow(),
});

/**
 * Fixed-window login throttling (AUDIT.md T9). Platform-level and pre-auth, so
 * deliberately no tenant_id: at the moment of a login attempt there is no
 * session to scope by. Keys look like `login:+99890…` / `ip:1.2.3.4`; rows are
 * upserted atomically (see `bumpThrottle` in apps/web) and deleted on success,
 * so the table stays a handful of hot rows, not a log.
 */
export const authThrottle = pgTable('auth_throttle', {
  key: text('key').primaryKey(),
  windowStart: timestamp('window_start', { withTimezone: true })
    .notNull()
    .defaultNow(),
  count: integer('count').notNull().default(1),
});

/**
 * grammY session state, persisted so a deploy doesn't wipe half-finished
 * multi-step flows (AUDIT.md T16) — a customer mid-"send your track codes"
 * used to land back at square one whenever the bot restarted. `key` is the
 * grammY session key (the chat id as a string); `data` is the serialized
 * `SessionData` owned by apps/bot. Rows are tiny and short-lived: the hourly
 * sweep deletes anything untouched for 30 days.
 */
export const botSessions = pgTable(
  'bot_sessions',
  {
    tenantId: uuid('tenant_id')
      .notNull()
      .references(() => tenants.id, { onDelete: 'cascade' }),
    key: text('key').notNull(),
    data: jsonb('data').$type<Record<string, unknown>>().notNull(),
    updatedAt: timestamp('updated_at', { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [primaryKey({ columns: [t.tenantId, t.key] })],
);

/**
 * Outcome log for every outbound bot message (AUDIT.md T13). Before this, a
 * customer who blocked the bot was silently dropped in the worker and the
 * tenant had no way to see that "notified" never happened. One row per
 * delivery attempt's FINAL outcome (not per retry), written by the worker.
 */
export const messageLog = pgTable(
  'message_log',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    tenantId: uuid('tenant_id')
      .notNull()
      .references(() => tenants.id, { onDelete: 'cascade' }),
    customerId: uuid('customer_id')
      .notNull()
      .references(() => customers.id, { onDelete: 'cascade' }),
    kind: messageKind('kind').notNull(),
    status: messageDeliveryStatus('status').notNull(),
    /** The track a `notify` was about; null for reminders/broadcasts. */
    trackId: uuid('track_id').references(() => tracks.id, {
      onDelete: 'set null',
    }),
    /** The campaign a `broadcast` delivery belongs to. */
    broadcastId: uuid('broadcast_id').references(() => broadcasts.id, {
      onDelete: 'cascade',
    }),
    /** The staff message a `ticket` delivery carried (SPEC §5.16/H4). */
    ticketMessageId: uuid('ticket_message_id').references(
      () => ticketMessages.id,
      { onDelete: 'cascade' },
    ),
    /** Short technical reason (Telegram error description), for diagnosis. */
    error: text('error'),
    createdAt: timestamp('created_at', { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [
    // The customer page reads "last N messages to this person".
    index('message_log_customer_idx').on(t.tenantId, t.customerId, t.createdAt),
  ],
);

// --- Relations (for typed relational queries) ------------------------------

export const tenantsRelations = relations(tenants, ({ many }) => ({
  adminUsers: many(adminUsers),
  customers: many(customers),
  tracks: many(tracks),
  payments: many(payments),
  tariffs: many(tariffs),
  batches: many(batches),
  broadcasts: many(broadcasts),
}));

export const tariffsRelations = relations(tariffs, ({ one, many }) => ({
  tenant: one(tenants, { fields: [tariffs.tenantId], references: [tenants.id] }),
  tracks: many(tracks),
}));

export const batchesRelations = relations(batches, ({ one, many }) => ({
  tenant: one(tenants, { fields: [batches.tenantId], references: [tenants.id] }),
  tracks: many(tracks),
}));

export const customersRelations = relations(customers, ({ one, many }) => ({
  tenant: one(tenants, {
    fields: [customers.tenantId],
    references: [tenants.id],
  }),
  tracks: many(tracks),
  payments: many(payments),
}));

export const tracksRelations = relations(tracks, ({ one, many }) => ({
  tenant: one(tenants, { fields: [tracks.tenantId], references: [tenants.id] }),
  customer: one(customers, {
    fields: [tracks.customerId],
    references: [customers.id],
  }),
  tariff: one(tariffs, {
    fields: [tracks.tariffId],
    references: [tariffs.id],
  }),
  batch: one(batches, {
    fields: [tracks.batchId],
    references: [batches.id],
  }),
  events: many(trackEvents),
}));

export const trackEventsRelations = relations(trackEvents, ({ one }) => ({
  track: one(tracks, {
    fields: [trackEvents.trackId],
    references: [tracks.id],
  }),
}));

export const paymentsRelations = relations(payments, ({ one }) => ({
  tenant: one(tenants, {
    fields: [payments.tenantId],
    references: [tenants.id],
  }),
  customer: one(customers, {
    fields: [payments.customerId],
    references: [customers.id],
  }),
}));

export const broadcastsRelations = relations(broadcasts, ({ one }) => ({
  tenant: one(tenants, {
    fields: [broadcasts.tenantId],
    references: [tenants.id],
  }),
}));

// --- Inferred types --------------------------------------------------------

export type Tenant = typeof tenants.$inferSelect;
export type NewTenant = typeof tenants.$inferInsert;
export type Tariff = typeof tariffs.$inferSelect;
export type NewTariff = typeof tariffs.$inferInsert;
export type Batch = typeof batches.$inferSelect;
export type NewBatch = typeof batches.$inferInsert;
export type AdminUser = typeof adminUsers.$inferSelect;
export type NewAdminUser = typeof adminUsers.$inferInsert;
export type AdminInvite = typeof adminInvites.$inferSelect;
export type NewAdminInvite = typeof adminInvites.$inferInsert;
export type Customer = typeof customers.$inferSelect;
export type NewCustomer = typeof customers.$inferInsert;
export type Track = typeof tracks.$inferSelect;
export type NewTrack = typeof tracks.$inferInsert;
export type TrackEvent = typeof trackEvents.$inferSelect;
export type NewTrackEvent = typeof trackEvents.$inferInsert;
export type Payment = typeof payments.$inferSelect;
export type NewPayment = typeof payments.$inferInsert;
export type Broadcast = typeof broadcasts.$inferSelect;
export type NewBroadcast = typeof broadcasts.$inferInsert;
export type Lead = typeof leads.$inferSelect;
export type NewLead = typeof leads.$inferInsert;
export type AuthThrottleRow = typeof authThrottle.$inferSelect;
export type BotSession = typeof botSessions.$inferSelect;
export type NewBotSession = typeof botSessions.$inferInsert;
export type MessageLogRow = typeof messageLog.$inferSelect;
export type NewMessageLogRow = typeof messageLog.$inferInsert;
export type MessageKind = (typeof messageKind.enumValues)[number];
export type MessageDeliveryStatus =
  (typeof messageDeliveryStatus.enumValues)[number];
export type TenantPlanValue = (typeof tenantPlan.enumValues)[number];

export type TrackStatus = (typeof trackStatus.enumValues)[number];
export type Currency = (typeof currency.enumValues)[number];
export type Transport = (typeof transport.enumValues)[number];
/** Every value the column accepts, `staff` included — see {@link adminRole}. */
export type AdminRoleValue = (typeof adminRole.enumValues)[number];
