/**
 * Drizzle schema for SERVIO Kargo (PostgreSQL).
 *
 * Core tables from CLAUDE.md "Data Model" plus the SPEC.md 7.8 `deleted_at`
 * soft-delete extension on `tracks`.
 *
 * Conventions:
 * - Primary keys: uuid (gen_random_uuid, built into Postgres).
 * - Money: bigint tiyin (integer minor unit, never floats) — CLAUDE.md rule 6.
 * - Telegram user ids: bigint (they exceed int4).
 * - Timestamps: timestamptz stored in UTC — SPEC 7.9.
 * - Every domain table carries tenant_id — CLAUDE.md rule 1.
 */

import { relations } from 'drizzle-orm';
import {
  bigint,
  boolean,
  date,
  index,
  integer,
  jsonb,
  pgEnum,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
  uuid,
} from 'drizzle-orm/pg-core';

// --- Enums -----------------------------------------------------------------

/** Fixed status pipeline (CLAUDE.md rule 7) in canonical order + side-states. */
export const trackStatus = pgEnum('track_status', [
  'CREATED',
  'CHINA_WAREHOUSE',
  'IN_TRANSIT',
  'TASHKENT_WAREHOUSE',
  'READY_FOR_PICKUP',
  'DELIVERED',
  'LOST',
  'RETURNED',
]);

export const adminRole = pgEnum('admin_role', ['owner', 'staff']);

export const paymentMethod = pgEnum('payment_method', [
  'cash',
  'click',
  'payme',
  'other',
]);

export const lang = pgEnum('lang', ['uz', 'ru']);

/** Tenant billing currency (SPEC §5.9 / §7.4). */
export const currency = pgEnum('currency', ['UZS', 'USD']);

/** Batch transport mode (SPEC §5.7). */
export const transport = pgEnum('transport', ['avia', 'avto', 'train']);

// --- Shared shapes ---------------------------------------------------------

/** Tenant-level configuration stored in `tenants.settings`. */
export type TenantSettings = {
  /** Telegram user ids allowed to use staff photo mode (SPEC 3.8). */
  staff_tg_ids: number[];
  /** Weekly auto-reminder config (SPEC 5.7 / 7.7). */
  reminders: {
    weekly_enabled: boolean;
    /** 1 = Monday … 7 = Sunday (ISO). */
    weekday: number;
    /** Hour of day in Asia/Tashkent, 0–23. */
    hour: number;
  };
  /**
   * China-warehouse address template rendered in the bot (SPEC 3.10 / 5.9).
   * `{client_code}` is substituted with the customer's code. Optional — older
   * rows and freshly onboarded tenants may not have it set yet.
   */
  china_address_template?: string;
  /** Free-text info block shown in the bot Info card (SPEC 3.5 / 5.9). */
  info_text?: string;
  /**
   * Marks a throwaway tenant generated by the demo importer
   * (packages/db/scripts/demo-import.ts) from a prospect's Telegram channel
   * history. Real onboarded tenants never set this. jsonb, so no migration.
   */
  demo?: boolean;
};

// --- Tables ----------------------------------------------------------------

export const tenants = pgTable('tenants', {
  id: uuid('id').primaryKey().defaultRandom(),
  name: text('name').notNull(),
  // Client-code prefix (2–4 latin letters, e.g. "DK"). client_code =
  // code_prefix + '-' + per-tenant sequence (SPEC 6, customers.client_code).
  codePrefix: text('code_prefix').notNull(),
  botToken: text('bot_token').notNull().unique(),
  botUsername: text('bot_username'),
  // Billing currency + USD rate (SPEC §5.9 / §7.4). Per-kg prices live on
  // `tariffs`, not here. `usd_rate_tiyin` = som per 1 USD, in tiyin; used only
  // when currency = 'USD'.
  currency: currency('currency').notNull().default('UZS'),
  usdRateTiyin: bigint('usd_rate_tiyin', { mode: 'number' }),
  pickupAddress: text('pickup_address'),
  workingHours: text('working_hours'),
  contactPhone: text('contact_phone'),
  settings: jsonb('settings').$type<TenantSettings>().notNull(),
  createdAt: timestamp('created_at', { withTimezone: true })
    .notNull()
    .defaultNow(),
});

/**
 * Per-tenant pricing tariffs (SPEC §5.9, §7.4). A tenant always has exactly one
 * active default tariff (enforced in the service layer, not the DB).
 * `price_per_kg_minor` is tiyin when the tenant is UZS, cents when USD.
 */
export const tariffs = pgTable('tariffs', {
  id: uuid('id').primaryKey().defaultRandom(),
  tenantId: uuid('tenant_id')
    .notNull()
    .references(() => tenants.id, { onDelete: 'cascade' }),
  name: text('name').notNull(),
  pricePerKgMinor: bigint('price_per_kg_minor', { mode: 'number' }).notNull(),
  isDefault: boolean('is_default').notNull().default(false),
  active: boolean('active').notNull().default(true),
  sort: integer('sort').notNull().default(0),
  createdAt: timestamp('created_at', { withTimezone: true })
    .notNull()
    .defaultNow(),
});

/**
 * Shipment batches ("Reyslar", SPEC §5.7, §7.10). Tracks optionally reference a
 * batch; a batch status change propagates to its non-terminal member tracks. A
 * batch's own status is limited to CHINA_WAREHOUSE | IN_TRANSIT |
 * TASHKENT_WAREHOUSE (enforced in the service layer).
 */
export const batches = pgTable('batches', {
  id: uuid('id').primaryKey().defaultRandom(),
  tenantId: uuid('tenant_id')
    .notNull()
    .references(() => tenants.id, { onDelete: 'cascade' }),
  name: text('name').notNull(),
  transport: transport('transport').notNull(),
  // Estimated arrival (date only). Shown in bot cards + IN_TRANSIT notifications.
  etaDate: date('eta_date'),
  status: trackStatus('status').notNull().default('CHINA_WAREHOUSE'),
  createdAt: timestamp('created_at', { withTimezone: true })
    .notNull()
    .defaultNow(),
});

export const adminUsers = pgTable('admin_users', {
  id: uuid('id').primaryKey().defaultRandom(),
  tenantId: uuid('tenant_id')
    .notNull()
    .references(() => tenants.id, { onDelete: 'cascade' }),
  phone: text('phone').notNull(),
  passwordHash: text('password_hash').notNull(),
  role: adminRole('role').notNull().default('staff'),
  createdAt: timestamp('created_at', { withTimezone: true })
    .notNull()
    .defaultNow(),
});

export const customers = pgTable(
  'customers',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    tenantId: uuid('tenant_id')
      .notNull()
      .references(() => tenants.id, { onDelete: 'cascade' }),
    tgUserId: bigint('tg_user_id', { mode: 'number' }),
    phone: text('phone'),
    fullName: text('full_name'),
    clientCode: text('client_code').notNull(),
    lang: lang('lang').notNull().default('uz'),
    createdAt: timestamp('created_at', { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => ({
    // client_code is unique within a tenant.
    clientCodeUq: uniqueIndex('customers_tenant_client_code_uq').on(
      t.tenantId,
      t.clientCode,
    ),
    // A Telegram user maps to at most one customer per tenant.
    tgUserUq: uniqueIndex('customers_tenant_tg_user_uq').on(
      t.tenantId,
      t.tgUserId,
    ),
  }),
);

export const tracks = pgTable(
  'tracks',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    tenantId: uuid('tenant_id')
      .notNull()
      .references(() => tenants.id, { onDelete: 'cascade' }),
    // Nullable: codes can arrive before a customer claims them (CLAUDE.md).
    customerId: uuid('customer_id').references(() => customers.id, {
      onDelete: 'set null',
    }),
    // Pricing tariff (SPEC §7.4); set to the tenant's default when first weighed.
    tariffId: uuid('tariff_id').references(() => tariffs.id, {
      onDelete: 'set null',
    }),
    // Shipment batch (SPEC §7.10), optional.
    batchId: uuid('batch_id').references(() => batches.id, {
      onDelete: 'set null',
    }),
    codeNormalized: text('code_normalized').notNull(),
    codeOriginal: text('code_original').notNull(),
    currentStatus: trackStatus('current_status').notNull().default('CREATED'),
    weightGrams: integer('weight_grams'),
    // Som price, always populated once weighed (frozen for USD tenants, §7.4).
    priceTiyin: bigint('price_tiyin', { mode: 'number' }),
    // USD-mode extras: price in cents + the som-per-USD rate used at weighing.
    priceUsdCents: bigint('price_usd_cents', { mode: 'number' }),
    usdRateUsed: bigint('usd_rate_used', { mode: 'number' }),
    // Manual override (§7.4): admin typed a som price; suspends auto-recompute.
    priceManual: boolean('price_manual').notNull().default(false),
    photoPath: text('photo_path'),
    // SPEC 7.8 soft delete.
    deletedAt: timestamp('deleted_at', { withTimezone: true }),
    createdAt: timestamp('created_at', { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => ({
    // CLAUDE.md: codes unique per tenant; collisions across tenants are fine.
    codeUq: uniqueIndex('tracks_tenant_code_uq').on(
      t.tenantId,
      t.codeNormalized,
    ),
    customerIdx: index('tracks_customer_idx').on(t.customerId),
    batchIdx: index('tracks_batch_idx').on(t.batchId),
  }),
);

export const trackEvents = pgTable('track_events', {
  id: uuid('id').primaryKey().defaultRandom(),
  trackId: uuid('track_id')
    .notNull()
    .references(() => tracks.id, { onDelete: 'cascade' }),
  status: trackStatus('status').notNull(),
  meta: jsonb('meta'),
  // Free-form actor: 'system', an admin_user id, or a telegram id.
  createdBy: text('created_by'),
  createdAt: timestamp('created_at', { withTimezone: true })
    .notNull()
    .defaultNow(),
});

export const payments = pgTable('payments', {
  id: uuid('id').primaryKey().defaultRandom(),
  tenantId: uuid('tenant_id')
    .notNull()
    .references(() => tenants.id, { onDelete: 'cascade' }),
  customerId: uuid('customer_id')
    .notNull()
    .references(() => customers.id, { onDelete: 'cascade' }),
  amountTiyin: bigint('amount_tiyin', { mode: 'number' }).notNull(),
  method: paymentMethod('method').notNull().default('cash'),
  note: text('note'),
  createdAt: timestamp('created_at', { withTimezone: true })
    .notNull()
    .defaultNow(),
});

/**
 * Broadcast history (SPEC §5.8, §7.11). One row per admin broadcast; `sent_count`
 * is bumped by the bot worker as each recipient's message is delivered, so it
 * records the final delivered count.
 */
export const broadcasts = pgTable('broadcasts', {
  id: uuid('id').primaryKey().defaultRandom(),
  tenantId: uuid('tenant_id')
    .notNull()
    .references(() => tenants.id, { onDelete: 'cascade' }),
  text: text('text').notNull(),
  sentCount: integer('sent_count').notNull().default(0),
  createdAt: timestamp('created_at', { withTimezone: true })
    .notNull()
    .defaultNow(),
});

// --- Relations (for typed relational queries) ------------------------------

export const tenantsRelations = relations(tenants, ({ many }) => ({
  adminUsers: many(adminUsers),
  customers: many(customers),
  tracks: many(tracks),
  payments: many(payments),
  tariffs: many(tariffs),
  batches: many(batches),
  broadcasts: many(broadcasts),
}));

export const tariffsRelations = relations(tariffs, ({ one, many }) => ({
  tenant: one(tenants, { fields: [tariffs.tenantId], references: [tenants.id] }),
  tracks: many(tracks),
}));

export const batchesRelations = relations(batches, ({ one, many }) => ({
  tenant: one(tenants, { fields: [batches.tenantId], references: [tenants.id] }),
  tracks: many(tracks),
}));

export const customersRelations = relations(customers, ({ one, many }) => ({
  tenant: one(tenants, {
    fields: [customers.tenantId],
    references: [tenants.id],
  }),
  tracks: many(tracks),
  payments: many(payments),
}));

export const tracksRelations = relations(tracks, ({ one, many }) => ({
  tenant: one(tenants, { fields: [tracks.tenantId], references: [tenants.id] }),
  customer: one(customers, {
    fields: [tracks.customerId],
    references: [customers.id],
  }),
  tariff: one(tariffs, {
    fields: [tracks.tariffId],
    references: [tariffs.id],
  }),
  batch: one(batches, {
    fields: [tracks.batchId],
    references: [batches.id],
  }),
  events: many(trackEvents),
}));

export const trackEventsRelations = relations(trackEvents, ({ one }) => ({
  track: one(tracks, {
    fields: [trackEvents.trackId],
    references: [tracks.id],
  }),
}));

export const paymentsRelations = relations(payments, ({ one }) => ({
  tenant: one(tenants, {
    fields: [payments.tenantId],
    references: [tenants.id],
  }),
  customer: one(customers, {
    fields: [payments.customerId],
    references: [customers.id],
  }),
}));

export const broadcastsRelations = relations(broadcasts, ({ one }) => ({
  tenant: one(tenants, {
    fields: [broadcasts.tenantId],
    references: [tenants.id],
  }),
}));

// --- Inferred types --------------------------------------------------------

export type Tenant = typeof tenants.$inferSelect;
export type NewTenant = typeof tenants.$inferInsert;
export type Tariff = typeof tariffs.$inferSelect;
export type NewTariff = typeof tariffs.$inferInsert;
export type Batch = typeof batches.$inferSelect;
export type NewBatch = typeof batches.$inferInsert;
export type AdminUser = typeof adminUsers.$inferSelect;
export type NewAdminUser = typeof adminUsers.$inferInsert;
export type Customer = typeof customers.$inferSelect;
export type NewCustomer = typeof customers.$inferInsert;
export type Track = typeof tracks.$inferSelect;
export type NewTrack = typeof tracks.$inferInsert;
export type TrackEvent = typeof trackEvents.$inferSelect;
export type NewTrackEvent = typeof trackEvents.$inferInsert;
export type Payment = typeof payments.$inferSelect;
export type NewPayment = typeof payments.$inferInsert;
export type Broadcast = typeof broadcasts.$inferSelect;
export type NewBroadcast = typeof broadcasts.$inferInsert;

export type TrackStatus = (typeof trackStatus.enumValues)[number];
export type Currency = (typeof currency.enumValues)[number];
export type Transport = (typeof transport.enumValues)[number];
